### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by dmandrone** [kdkasad/docker-mod-jellyfin-jellyscrub#1]
Would you be able to confirm?

**Comment by kdkasad** [comment]
Did you install the Jellyscrub plugin for Jellyfin first? Just adding this Docker mod will not install Jellyscrub, as noted in the README.

If you did that and it still doesn't work, please provide some more details. Seeing your `docker-compose.yml` file would help.

**Comment by dmandrone** [comment]
Yes, I did.

Docker compose is below:
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=192.xxx.xxx.xx
    volumes:
      - /volume1/docker/jellyfin:/config
      - /volume1/data/media:/data/media
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096 #web port
    restart: unless-stopped

**Comment by dmandrone** [comment]
The variables were added to the docker container by editing it

**Comment by kdkasad** [comment]
Try adding the `DOCKER_MODS` variable to the compose file. LinuxServer.io containers install mods when they are booted, so editing the container while it's running won't work.

If that still doesn't work, then it may be a problem with this mod. The only supported way to install this mod is by adding the URL to the `DOCKER_MODS` variable in the `docker-compose.yml` file, as documented in the README.

**Comment by dmandrone** [comment]
Yeah I had done so since. Guess it's just broken

**Comment by kdkasad** [comment]
Again, I can't recreate the problem. Here's the `docker-compose.yml` file I used and it works fine:
```yml
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyscrubtest
    environment:
      - TZ=America/Los_Angeles
      - DOCKER_MODS=ghcr.io/kdkasad/docker-mods:jellyfin-jellyscrub
    volumes:
      - config:/config
      - tv:/data/tvshows
      - movies:/data/movies
    tmpfs:
      - /config/cache
      - /config/data/transcodes
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

volumes:
  config:
  tv:
  movies:
```
This is on a fresh install of Docker as well, so nothing else in my environment could be making it work.

Please try this Docker compose file. Once the container is started, run this command to verify that the mod works:
```sh
docker exec jellyscrubtest grep -cF 'Jellyscrub' /usr/share/jellyfin/web/index.html
```
It should print `1`. If it prints `0`, please attach the output of `docker logs jellyscrubtest`.
